spring:
    datasource:
        url: jdbc:mysql://localhost:3307/test?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        hikari:
            connection-timeout: 60000 # 60s
            maximum-pool-size: 5
    jpa:
        hibernate:
            ddl-auto: create-drop
